Deployment for goerli
keep-network/coverage-pools pull request #213
Opened 2022-07-21 13:12 UTC by nkuba

In this PR we add configuration that is needed for Goerli contracts deployment.

2022-07-29 12:23 UTC, michalinacienciala requested changes

2022-07-29 12:23 UTC, michalinacienciala commented on package.json
>    "devDependencies": {
We need to update `yarn.lock` as well

2022-07-29 13:13 UTC, michalinacienciala commented on hardhat.config.ts
>          ? [process.env.CONTRACT_OWNER_ACCOUNT_PRIVATE_KEY]
Do we want to make similar change to [this one](https://github.com/keep-network/keep-core/pull/3111) here?

2022-08-02 14:20 UTC, nkuba commented
Closing in favour of https://github.com/keep-network/coverage-pools/pull/214

2022-08-02 14:20 UTC, closed without merging